# A minimal left prompt
# format = """$character"""

# move the rest of the prompt to the right
# right_format = """$all"""




command_timeout = 50
#command_timeout = 100

[cmake]
disabled = true


[ruby]
symbol = "🔺 "


[nodejs]
symbol = "❖"
format = "[$symbol($version )]($style)"
disabled = true

[aws]
disabled = true

[gcloud]
disabled = false

[git_branch]
# symbol = "🌱 "
# symbol = "⎇ "
symbol = "⑂ "

[git_status]
ignore_submodules = true

[custom.git_author]
#  disabled = true
ignore_timeout = true
command = 'git config --get user.email' # shows output of command
style = 'dimmed white'
symbol = ' @ '
# symbol = '✍️ '
detect_folders = ['.git'] # can specify filters but wildcards are not supported
#when = ''' test "$HOME" = "$PWD" '''
#format = '  [$output]($style)'
