cask_args appdir: '/Applications'
tap 'homebrew/cask'
tap 'go-task/tap'
brew 'mas'

## Mac App Store
mas 'maccy', id: 1527619437 # Clipboard Manager
mas 'Things', id: 904280696 # todo list

## Casks
cask '1password'
cask 'contexts'
cask 'iterm2'
cask 'phoenix'
cask 'soulver'
cask 'spotify'
cask 'typora'
cask 'visual-studio-code'

# Sometimes!
# cask 'bettertouchtool' # To split mousewheel scroll direction vs trackpad direction.
# cask 'deckset'
# cask 'docker'
# cask 'firefox'
# cask 'gitup'
# cask 'google-drive-file-stream'
# cask 'istat-menus'
# cask 'karabiner-elements'
# cask 'opera'
# cask 'rubymine'
# cask 'transmission'
# cask 'twine'
# cask 'vlc'
